/************************************************************************************

                                  smb Utility

  File: string_j.h
  Description:
  History:

 ************************************************************************************/
#ifndef STRING_J_H
#define STRING_J_H

#define PROGRAMNAME  TEXT("SMB Utility")

#define STRING_VERSION_CONTRIBUTION TEXT("Multi-6502 CPU emulator by Neil Bradley (neil@synthcom.com)")

#define STRING_NULL    TEXT("")
#define STRING_UNKNOWN TEXT("不明")

#define STRING_LOGVIEW_FILESAVE TEXT("%sに保存しました。")
#define STRING_LOGVIEW_FILEOPEN TEXT("%sを開きました。")
#define STRING_LOGVIEW_LOADCHR  TEXT("%sから%.4xHﾊﾞｲﾄのCHRROMを読み込みました。")

//ｳｲﾝﾄﾞｳのﾀｲﾄﾙ
//
#define STRING_FILEOPENDIALOG_CHRLOAD TEXT("ｷｬﾗｸﾀﾛﾑの読み込み")
#define STRING_WINDOW_EMULATOR        TEXT("ｴﾐｭﾚｰﾀ")
#define STRING_WINDOW_OBJLIST         TEXT("ｵﾌﾞｼﾞｪｸﾄ ﾘｽﾄ")
#define STRING_WINDOW_OBJVIEW         TEXT("ｵﾌﾞｼﾞｪｸﾄ ﾋﾞｭｰ")

//
#define STRING_OBJVIEW_TITLE          TEXT("%s <%dﾍﾟｰｼﾞ>")
#define STRING_OBJVIEW_TITLE2         TEXT("%s <%d-%dﾍﾟｰｼﾞ>")
#define STRING_OBJVIEW_TOOLTIP        TEXT("%d,(%d,%d) %s")

//ｽﾃｰﾀｽﾊﾞｰ
#define STRING_STATUSBAR_EMULOAD  TEXT("ﾛｰﾄﾞしました。")
#define STRING_STATUSBAR_EMUSAVE  TEXT("ｾｰﾌﾞされました。")
#define STRING_STATUSBAR_FILESAVE TEXT("ﾌｧｲﾙに保存しました。")

//ﾌｧｲﾙｴﾗｰ
#define STRING_FILEERROR_SAVE       TEXT("上書き保存できません。")
#define STRING_FILEERROR_SAVEAS     TEXT("保存できません。")
#define STRING_FILEERROR_FILEFORMAT TEXT("ﾌｧｲﾙの形式にｴﾗｰがあります。")
#define STRING_FILEERROR_NOTFOUND   TEXT("ﾌｧｲﾙが見つかりません。")

//ﾒｯｾｰｼﾞ
#define STRING_CONFIRM_SAVE         TEXT("上書き保存しますか？")
#define STRING_CONFIRM_EXIT         TEXT("変更を保存しますか？")
#define STRING_CONFIRM_RELOAD       TEXT("ﾌｧｲﾙが外部ｴﾃﾞｨﾀで更新されています。\n再ﾛｰﾄﾞしますか。（再ﾛｰﾄﾞすると、未保存の内容は失われます。）")
#define STRING_CONFIRM_DEMORECORD   TEXT("ﾃﾞﾓのﾚｺｰﾃﾞｨﾝｸﾞを開始します。")
#define STRING_CONFIRM_DEMORECORD2  TEXT("ﾃﾞﾓのﾚｺｰﾃﾞｨﾝｸﾞを終了しました。")
#define STRING_CONFIRM_UPDATEWORLD  TEXT("ﾜｰﾙﾄﾞの区分の更新を行います。")

//ｵﾌﾟｼｮﾝ ﾌﾟﾛﾊﾟﾃｲ ｼｰﾄ
#define STRING_OPTIONDIALOG_TITLE       TEXT("ｵﾌﾟｼｮﾝ")
#define STRING_OPTIONDIALOG_EMULATOR    TEXT("ｴﾐｭﾚｰﾀ")
#define STRING_OPTIONDIALOG_EDITOR      TEXT("ｴﾃﾞｨﾀ")
#define STRING_OPTIONDIALOG_APPLICATION TEXT("ｱﾌﾟﾘｹｰｼｮﾝ")
#define STRING_OPTIONDIALOG_OBJECTVIEW  TEXT("ｵﾌﾞｼﾞｪｸﾄﾋﾞｭｰ")

//ﾂｰﾙﾁｯﾌﾟ
#define STRING_TOOLTIP_OPEN              TEXT("開く")
#define STRING_TOOLTIP_SAVE              TEXT("上書き保存")
#define STRING_TOOLTIP_ROOM              TEXT("ﾙｰﾑの変更")
#define STRING_TOOLTIP_BADGUYS           TEXT("敵")
#define STRING_TOOLTIP_MAP               TEXT("地形")
#define STRING_TOOLTIP_TESTPLAY          TEXT("ﾃｽﾄﾌﾟﾚｲ")
#define STRING_TOOLTIP_PAGETESTPLAY      TEXT("ﾍﾟｰｼﾞﾃｽﾄﾌﾟﾚｲ")
#define STRING_TOOLTIP_HALFPOINTTESTPLAY TEXT("途中ﾍﾟｰｼﾞﾃｽﾄﾌﾟﾚｲ")
#define STRING_TOOLTIP_STOP              TEXT("停止")
#define STRING_TOOLTIP_TESTPLAYSETTING   TEXT("ﾃｽﾄﾌﾟﾚｲの設定")
//#define STRING_TOOLTIP_ETC               TEXT("､その他")

// オブジェクトを送るダイアログ
#define STRING_SENDOBJECT_SRCERROR TEXT("送り元のｵﾌﾞｼﾞｪｸﾄは、ﾍﾟｰｼﾞの関係に影響を与えるｵﾌﾞｼﾞｪｸﾄです。")
#define STRING_SENDOBJECT_DSTERROR TEXT("送り先のﾍﾟｰｼﾞには、ｵﾌﾞｼﾞｪｸﾄがありません。")
#define STRING_SENDOBJECT_OVEROBJ  TEXT("送り先のﾙｰﾑには、これ以上ｵﾌﾞｼﾞｪｸﾄを送ることができません。")

#define STRING_UNDO_MENUTEXT              TEXT("元に戻す(&U) \"%s\"")
#define STRING_UNDONAME_KEYEDIT           TEXT("ｷｰﾎﾞ-ﾄﾞ入力")
#define STRING_UNDONAME_DLGEDIT           TEXT("ﾀﾞｲｱﾛｸﾞ入力")
#define STRING_UNDONAME_SENDOBJ           TEXT("ｵﾌﾞｼﾞｪｸﾄを送る")
#define STRING_UNDONAME_HEADDLG           TEXT("設定")
#define STRING_UNDONAME_CHRLOAD           TEXT("ｷｬﾗｸﾀﾛﾑの読み込み")
#define STRING_UNDONAME_TOOLSTR           TEXT("文字列の編集")
#define STRING_UNDONAME_TOOLLOOPBIN       TEXT("ﾙｰﾌﾟの編集(ﾊﾞｲﾅﾘ)")
#define STRING_UNDONAME_TOOLWORLD         TEXT("ﾜｰﾙﾄﾞの区分の自動更新")
#define STRING_UNDONAME_TOOLAREAROOM      TEXT("ｴﾘｱの開始ﾙｰﾑの編集")
#define STRING_UNDONAME_TOOLDEMORECORDER  TEXT("ﾃﾞﾓ ﾚｺｰﾀﾞｰ")
#define STRING_UNDONAME_TOOLOTHER         TEXT("その他の設定")
//#define STRING_UNDONAME_TOOLGLOBAL        TEXT("全般の設定")


#define STRING_POLEGFX_DEFAULT TEXT("ﾃﾞﾌｫﾙﾄ")
#define STRING_POLEGFX_ROPE    TEXT("ひも")
#define STRING_POLEGFX_TREE    TEXT("木")
#define STRING_POLEGFX_OTHER   TEXT("その他")

#define STRING_SETTING_WORLDX   TEXT("ﾜｰﾙﾄﾞ%d")
#define STRING_SETTING_WARPZONE TEXT("ﾜｰﾌﾟｿﾞｰﾝ")
#define STRING_SETTING_1UP      TEXT("1UPｷﾉｺ")
#define STRING_SETTING_KOOPA    TEXT("ｸｯﾊﾟ")
#define STRING_SETTING_WORLD    TEXT("ﾜｰﾙﾄﾞ")
#define STRING_SETTING_OTHER    TEXT("その他")
#define STRING_SETTING_TITLE    TEXT("その他の設定")


#define STRING_STRINGDATA_01 TEXT("MARIO(ｽﾃｰﾀｽ)")
#define STRING_STRINGDATA_02 TEXT("MARIO(2P時のﾀｲﾑｱｯﾌﾟ)")
#define STRING_STRINGDATA_03 TEXT("MARIO(ｹﾞｰﾑｵｰﾊﾞｰ時)")
#define STRING_STRINGDATA_04 TEXT("LUIGI(ｽﾃｰﾀｽ表示/2P時のﾀｲﾑｱｯﾌﾟ/ｹﾞｰﾑｵｰﾊﾞｰ)")
#define STRING_STRINGDATA_05 TEXT("WORLD  TIME(ｽﾃｰﾀｽ)")
#define STRING_STRINGDATA_06 TEXT("WORLD(ｲﾝﾄﾛ画面)")
#define STRING_STRINGDATA_07 TEXT("TIME UP")
#define STRING_STRINGDATA_08 TEXT("GAME OVER")
#define STRING_STRINGDATA_09 TEXT("WELCOME TO WARP ZONE!")
#define STRING_STRINGDATA_10 TEXT("THANK YOU MARIO!")
#define STRING_STRINGDATA_11 TEXT("THANK YOU LUIGI!")
#define STRING_STRINGDATA_12 TEXT("BUT OUR PRINCESS IS IN")
#define STRING_STRINGDATA_13 TEXT("ANOTHER CASTLE!")
#define STRING_STRINGDATA_14 TEXT("YOUR QUEST IS OVER.")
#define STRING_STRINGDATA_15 TEXT("WE PRESENT YOU A NEW QUEST.")
#define STRING_STRINGDATA_16 TEXT("PUSH BUTTON B")
#define STRING_STRINGDATA_17 TEXT("TO SELECT A WORLD")
#define STRING_STRINGDATA_18 TEXT("著作権表示(ﾀｲﾄﾙ画面)")
#define STRING_STRINGDATA_19 TEXT("1 PLAYER GAME(ﾀｲﾄﾙ画面)")
#define STRING_STRINGDATA_20 TEXT("2 PLAYER GAME(ﾀｲﾄﾙ画面)")


#define STRING_TESTPLAYSETTING_MARIO      TEXT("ﾏﾘｵ")
#define STRING_TESTPLAYSETTING_SUPERMARIO TEXT("ｽｰﾊﾟｰﾏﾘｵ")
#define STRING_TESTPLAYSETTING_FIREMARIO  TEXT("ﾌｧｲｱｰﾏﾘｵ")
#define STRING_TESTPLAYSETTING_NONE       TEXT("無効")
#define STRING_TESTPLAYSETTING_POS        TEXT("位置")
#define STRING_TESTPLAYSETTING_DOT        TEXT("ﾄﾞｯﾄ")
                                          
#define STRING_EMULATOROPTION_JOYSTICK   TEXT("ｼﾞｮｲｽﾃｨｯｸ")

#define STRING_KEYCONFIG_EMU_A              TEXT("Aﾎﾞﾀﾝ")
#define STRING_KEYCONFIG_EMU_B              TEXT("Bﾎﾞﾀﾝ")
#define STRING_KEYCONFIG_EMU_SELECT         TEXT("ｾﾚｸﾄﾎﾞﾀﾝ")
#define STRING_KEYCONFIG_EMU_START          TEXT("ｽﾀｰﾄﾎﾞﾀﾝ")
#define STRING_KEYCONFIG_EMU_UP             TEXT("上")
#define STRING_KEYCONFIG_EMU_DOWN           TEXT("下")
#define STRING_KEYCONFIG_EMU_LEFT           TEXT("左")
#define STRING_KEYCONFIG_EMU_RIGHT          TEXT("右")
#define STRING_KEYCONFIG_EDIT_ADD1          TEXT("種類を+1")
#define STRING_KEYCONFIG_EDIT_DEC1          TEXT("種類を-1")
#define STRING_KEYCONFIG_EDIT_ADD16         TEXT("種類を+16")
#define STRING_KEYCONFIG_EDIT_DEC16         TEXT("種類を-16")
#define STRING_KEYCONFIG_EDIT_UP            TEXT("位置を上へ")
#define STRING_KEYCONFIG_EDIT_DOWN          TEXT("位置を下へ")
#define STRING_KEYCONFIG_EDIT_LEFT          TEXT("位置を左へ")
#define STRING_KEYCONFIG_EDIT_RIGHT         TEXT("位置を右へ")
#define STRING_KEYCONFIG_EDIT_NEXTPAGE      TEXT("次のﾍﾟｰｼﾞへ")
#define STRING_KEYCONFIG_EDIT_PREVPAGE      TEXT("前のﾍﾟｰｼﾞへ")
#define STRING_KEYCONFIG_EDIT_NEXTOBJ       TEXT("次のｵﾌﾞｼﾞｪｸﾄへ")
#define STRING_KEYCONFIG_EDIT_PREVOBJ       TEXT("前のｵﾌﾞｼﾞｪｸﾄへ")
#define STRING_KEYCONFIG_EDIT_SAVEFILE      TEXT("ﾌｧｲﾙ: 上書き保存")
#define STRING_KEYCONFIG_EDIT_UNDO          TEXT("編集: 元に戻す")
#define STRING_KEYCONFIG_EDIT_ROOM          TEXT("編集: ﾙｰﾑを開く")
#define STRING_KEYCONFIG_EDIT_BADGUYS       TEXT("編集: 敵")
#define STRING_KEYCONFIG_EDIT_MAP           TEXT("編集: 地形")
#define STRING_KEYCONFIG_EDIT_TESTPLAY      TEXT("ｴﾐｭﾚｰﾀ: ﾃｽﾄﾌﾟﾚｲ")
#define STRING_KEYCONFIG_EDIT_PAGETESTPLAY  TEXT("ｴﾐｭﾚｰﾀ: ﾍﾟｰｼﾞﾃｽﾄﾌﾟﾚｲ")
#define STRING_KEYCONFIG_EDIT_PAGETESTPLAY2 TEXT("ｴﾐｭﾚｰﾀ: 途中ﾍﾟｰｼﾞﾃｽﾄﾌﾟﾚｲ")
#define STRING_KEYCONFIG_EDIT_STOP          TEXT("ｴﾐｭﾚｰﾀ: 停止")
#define STRING_KEYCONFIG_EDIT_SAVEEMU       TEXT("ｴﾐｭﾚｰﾀ: ｾｰﾌﾞ")
#define STRING_KEYCONFIG_EDIT_LOADEMU       TEXT("ｴﾐｭﾚｰﾀ: ﾛｰﾄﾞ")
#define STRING_KEYCONFIG_EDIT_EMUSETTING    TEXT("ｴﾐｭﾚｰﾀ: ﾃｽﾄﾌﾟﾚｲの設定")
#define STRING_KEYCONFIG_EDIT_NEXTWIN       TEXT("ｳｲﾝﾄﾞｳ: 次へ")
#define STRING_KEYCONFIG_EDIT_PREVWIN       TEXT("ｳｲﾝﾄﾞｳ: 前へ")
#define STRING_KEYCONFIG_KEYACCEL           TEXT("ｷｰﾎﾞｰﾄﾞｱｸｾﾗﾚｰﾀ")
#define STRING_KEYCONFIG_EMULATOR           TEXT("ｴﾐｭﾚｰﾀ")
#define STRING_KEYCONFIG_OVERLAPPED         TEXT("%sの\"%s\"と重複しています。")
#define STRING_KEYCONFIG_INITIALIZE         TEXT("ﾌﾟﾘｾｯﾄｷｰをﾛｰﾄﾞします。よろしいですか?")
#define STRING_KEYCONFIG_NOTIFY             TEXT("次回の起動から有効になります。")

#define STRING_KEYCONFIG_PRESET_DESKTOP     TEXT("ﾃﾞｽｸﾄｯﾌﾟ(ﾃﾝｷｰ編集)")
#define STRING_KEYCONFIG_PRESET_NOTE        TEXT("ﾉｰﾄ(文字ｷｰ編集)")

#define STRING_KEYCONFIG_WHEEL_NONE         TEXT("なし")
#define STRING_KEYCONFIG_WHEEL_SHIFT        TEXT("+ｼﾌﾄ")
#define STRING_KEYCONFIG_WHEEL_CTRL         TEXT("+ｺﾝﾄﾛｰﾙ")
#define STRING_KEYCONFIG_WHEEL_SHIFTCTRL    TEXT("+ｼﾌﾄ+ｺﾝﾄﾛｰﾙ")
#define STRING_KEYCONFIG_WHEEL_TYPE1        TEXT("種類を増減1")
#define STRING_KEYCONFIG_WHEEL_TYPE16       TEXT("種類を増減16")
#define STRING_KEYCONFIG_WHEEL_PAGE         TEXT("ﾍﾟｰｼﾞごとの移動")
#define STRING_KEYCONFIG_WHEEL_OBJ          TEXT("ｵﾌﾞｼﾞｪｸﾄごとの移動")

#define STRING_KEYCONFIG_BUTTONX            TEXT("ﾎﾞﾀﾝ%d")


#define STRING_OBJLIST_LENNAME   TEXT("長さ%dの%s")
#define STRING_OBJLIST_UNKNOWN   TEXT("不明なｵﾌﾞｼﾞｪｸﾄ")
#define STRING_OBJLIST_CRASH     TEXT("*暴走")
#define STRING_OBJLIST_BACK      TEXT("背景:%s")
#define STRING_OBJLIST_VIEWBLOCK TEXT("景色:%s ﾌﾞﾛｯｸ:%s")
#define STRING_OBJLIST_ROPE      TEXT("縦位置0、長さ13のリフトの縦ロープ")
#define STRING_OBJLIST_LENCASTLE TEXT("長さ%dの城")
#define STRING_OBJLIST_STEP      TEXT("幅%d・高さ%dの階段")
#define STRING_OBJLIST_STEP98    TEXT("幅9・高さ8の階段")
#define STRING_OBJLIST_STEP98_2  TEXT("*幅9・高さ8の階段")
#define STRING_OBJLIST_NONE      TEXT("*無し")

#define STRING_OBJLIST_ROOM        TEXT("ﾙｰﾑ間移動の命令[%.2xH(%s),w=%d,p=%d]")
#define STRING_OBJLIST_PAGECOMMAND TEXT("ﾍﾟｰｼﾞ送りｺﾏﾝﾄﾞ : %.2d")
#define STRING_OBJLIST_HARD        TEXT("（5-3以降出現）")

#define STRING_AREASORT_TITLE TEXT("ｴﾘｱの開始ﾙｰﾑの指定")

#define STRING_SEA         TEXT("海")
#define STRING_SKY         TEXT("地上")
#define STRING_UNDERGROUND TEXT("地下")
#define STRING_CASTLE      TEXT("城")

#define STRING_OBJLIST_COLUMN_BIN  TEXT("ﾊﾞｲﾅﾘ")
#define STRING_OBJLIST_COLUMN_PAGE TEXT("ﾍﾟｰｼﾞ")
#define STRING_OBJLIST_COLUMN_POS  TEXT("位置")
#define STRING_OBJLIST_COLUMN_TYPE TEXT("種類")

#define STRING_OBJDATA_MAP_B_01 TEXT("?ﾌﾞﾛｯｸ(ﾊﾟﾜｰｷﾉｺ)")
#define STRING_OBJDATA_MAP_B_02 TEXT("?ﾌﾞﾛｯｸ(ｺｲﾝ1枚)")
#define STRING_OBJDATA_MAP_B_03 TEXT("隠れﾌﾞﾛｯｸ(ｺｲﾝ1枚)")
#define STRING_OBJDATA_MAP_B_04 TEXT("隠れﾌﾞﾛｯｸ(1UPｷﾉｺ)")
#define STRING_OBJDATA_MAP_B_05 TEXT("ﾚﾝｶﾞﾌﾞﾛｯｸ(ﾊﾟﾜｰｷﾉｺ)")
#define STRING_OBJDATA_MAP_B_06 TEXT("ﾚﾝｶﾞﾌﾞﾛｯｸ(豆の木)")
#define STRING_OBJDATA_MAP_B_07 TEXT("ﾚﾝｶﾞﾌﾞﾛｯｸ(ｽﾀｰ)")
#define STRING_OBJDATA_MAP_B_08 TEXT("ﾚﾝｶﾞﾌﾞﾛｯｸ(10ｺｲﾝ)")
#define STRING_OBJDATA_MAP_B_09 TEXT("ﾚﾝｶﾞﾌﾞﾛｯｸ(1UPｷﾉｺ)")
#define STRING_OBJDATA_MAP_B_10 TEXT("横から入る土管")
#define STRING_OBJDATA_MAP_B_11 TEXT("使用済みﾌﾞﾛｯｸ")
#define STRING_OBJDATA_MAP_B_12 TEXT("ｼﾞｬﾝﾌﾟ台")
#define STRING_OBJDATA_MAP_B_13 TEXT("逆L字型土管")
#define STRING_OBJDATA_MAP_B_14 TEXT("ﾎﾟｰﾙ")
#define STRING_OBJDATA_MAP_B_15 TEXT("*無し")
#define STRING_OBJDATA_MAP_B_16 TEXT("*無し")
#define STRING_OBJDATA_MAP_B_17 TEXT("ｱｽﾚﾁｯｸ台(砲台)")
#define STRING_OBJDATA_MAP_B_18 TEXT("横にならんだﾚﾝｶﾞﾌﾞﾛｯｸ(海草)")
#define STRING_OBJDATA_MAP_B_19 TEXT("横にならんだ壊せないﾌﾞﾛｯｸ")
#define STRING_OBJDATA_MAP_B_20 TEXT("横にならんだｺｲﾝ列")
#define STRING_OBJDATA_MAP_B_21 TEXT("縦にならんだﾚﾝｶﾞﾌﾞﾛｯｸ(海草)")
#define STRING_OBJDATA_MAP_B_22 TEXT("縦にならんだ壊せないﾌﾞﾛｯｸ")
#define STRING_OBJDATA_MAP_B_23 TEXT("入れない土管")
#define STRING_OBJDATA_MAP_B_24 TEXT("入れる土管")

#define STRING_OBJDATA_HELP_B12 TEXT("ｷｬﾗｸﾀの１つ。ｷｬﾗｸﾀｵｰﾊﾞｰで表示されなくなると、ﾏﾘｵが挟まって出れなくなるので注意。")
#define STRING_OBJDATA_HELP_B13 TEXT("高さ9固定。横からでも上からでも入れる。(横位置＋2)から2ｷｬﾗ分は、先に指定された障害物を消す。")
#define STRING_OBJDATA_HELP_B14 TEXT("やたらと使用しないこと。1ﾙｰﾑに2回以上使用すると暴走しやすくなるので注意。")
#define STRING_OBJDATA_HELP_B23 TEXT("長さを1にしても必ず2になる。")
//#define STRING_OBJDATA_HELP_B24 TEXT("長さを1にしても必ず2になる。")

#define STRING_OBJDATA_MAP_C_01 TEXT("穴")
#define STRING_OBJDATA_MAP_C_02 TEXT("天秤ﾘﾌﾄの横ﾛｰﾌﾟ")
#define STRING_OBJDATA_MAP_C_03 TEXT("吊り橋(縦位置7)")
#define STRING_OBJDATA_MAP_C_04 TEXT("吊り橋(縦位置8)")
#define STRING_OBJDATA_MAP_C_05 TEXT("吊り橋(縦位置10)")
#define STRING_OBJDATA_MAP_C_06 TEXT("海（縦位置10)")
#define STRING_OBJDATA_MAP_C_07 TEXT("横に並んだ?ﾌﾞﾛｯｸ(ｺｲﾝ、縦位置3)")
#define STRING_OBJDATA_MAP_C_08 TEXT("横に並んだ?ﾌﾞﾛｯｸ(ｺｲﾝ、縦位置7)")

#define STRING_OBJDATA_HELP_C01 TEXT("縦位置8から12の先指定したすべてのﾏｯﾌﾟｷｬﾗを消す。")
#define STRING_OBJDATA_HELP_C02 TEXT("縦位置0固定")
#define STRING_OBJDATA_HELP_C06 TEXT("縦位置10から12の先指定したすべてのﾏｯﾌﾟｷｬﾗを消す。")

#define STRING_OBJDATA_MAP_D_01 TEXT("ﾍﾟｰｼﾞ送りｺﾏﾝﾄﾞ")
#define STRING_OBJDATA_MAP_D_02 TEXT("逆L字型土管")
#define STRING_OBJDATA_MAP_D_03 TEXT("ﾎﾟｰﾙ")
#define STRING_OBJDATA_MAP_D_04 TEXT("ﾊﾝﾏｰ")
#define STRING_OBJDATA_MAP_D_05 TEXT("斜めのﾛｰﾌﾟ")
#define STRING_OBJDATA_MAP_D_06 TEXT("ｸｯﾊﾟの橋")
#define STRING_OBJDATA_MAP_D_07 TEXT("画面ｽｸﾛｰﾙをとめる(ﾜｰﾌﾟｿﾞ-ﾝ)")
#define STRING_OBJDATA_MAP_D_08 TEXT("画面ｽｸﾛｰﾙをとめる")
//#define STRING_OBJDATA_MAP_D_09 TEXT("画面ｽｸﾛｰﾙをとめる")
#define STRING_OBJDATA_MAP_D_10 TEXT("赤いﾌﾟｸﾌﾟｸ(空飛び)")
#define STRING_OBJDATA_MAP_D_11 TEXT("ｷﾗｰ(ﾌﾟｸﾌﾟｸ)連続")
#define STRING_OBJDATA_MAP_D_12 TEXT("連続出現ｷｬﾗを出なくする")
#define STRING_OBJDATA_MAP_D_13 TEXT("ﾙｰﾌﾟｺﾏﾝﾄﾞ")
#define STRING_OBJDATA_MAP_D_14 TEXT("?")
#define STRING_OBJDATA_MAP_D_15 TEXT("*暴走")
//#define STRING_OBJDATA_MAP_D_16 TEXT("*暴走")
//#define STRING_OBJDATA_MAP_D_17 TEXT("*暴走")

#define STRING_OBJDATA_HELP_D01 TEXT("指定ﾍﾟｰｼﾞまでﾏｯﾌﾟを送る。")
#define STRING_OBJDATA_HELP_D03 TEXT("やたらと使用しない事。1ﾙｰﾑに2回以上使用すると暴走しやすくなるので注意。")
#define STRING_OBJDATA_HELP_D04 TEXT("縦位置6固定、偶数ﾍﾟｰｼﾞに設置しないと橋が落ちない。")
#define STRING_OBJDATA_HELP_D05 TEXT("縦位置7固定")
#define STRING_OBJDATA_HELP_D06 TEXT("縦位置8、長さ13固定、偶数ﾍﾟｰｼﾞに設置しないと橋が落ちない。")
#define STRING_OBJDATA_HELP_D12 TEXT("連続出現ｷｬﾗを出した後、暴走を防ぐためにﾎﾟｰﾙを出す前に指定。")
#define STRING_OBJDATA_HELP_D13 TEXT("ﾍﾟｰｼﾞ送りｺﾏﾝﾄﾞとｾｯﾄでﾙｰﾌﾟを形成する。")

#define STRING_OBJDATA_MAP_E_01 TEXT("基本ﾌﾞﾛｯｸと景色の変更")
#define STRING_OBJDATA_MAP_E_02 TEXT("背景の変更")

#define STRING_OBJDATA_MAP_F_01 TEXT("ﾘﾌﾄの縦ﾛｰﾌﾟ")
#define STRING_OBJDATA_MAP_F_02 TEXT("天秤ﾘﾌﾄの縦ﾛｰﾌﾟ")
#define STRING_OBJDATA_MAP_F_03 TEXT("城")
#define STRING_OBJDATA_MAP_F_04 TEXT("幅n,高さnの階段")
#define STRING_OBJDATA_MAP_F_05 TEXT("幅9、高さ8の階段")
#define STRING_OBJDATA_MAP_F_06 TEXT("長い逆L字土管")
#define STRING_OBJDATA_MAP_F_07 TEXT("縦に並んだ丸ｷｬﾗ")
#define STRING_OBJDATA_MAP_F_08 TEXT("無し")
//#define STRING_OBJDATA_MAP_F_09 "無し")

#define STRING_OBJDATA_HELP_F01 TEXT("縦位置0、長さ13固定。指定横位置において、先指定したすべてのﾏｯﾌﾟｷｬﾗを消す。")
#define STRING_OBJDATA_HELP_F02 TEXT("縦位置1固定。指定横位置において、先指定したすべてのﾏｯﾌﾟｷｬﾗを消す。")
#define STRING_OBJDATA_HELP_F03 TEXT("やたらと使用しないこと。多く使用すると暴走しやすくなる。")
#define STRING_OBJDATA_HELP_F05 TEXT("長さを0以外に設定すると、後のｴﾘｱの表示がおかしくなります。")
#define STRING_OBJDATA_HELP_F07 TEXT("ﾂﾀのようにつかまって上下移動が可能。縦位置2固定")

#define STRING_OBJDATA_BB_01 TEXT("ﾌﾞﾛｯｸ無し")
#define STRING_OBJDATA_BB_02 TEXT("地面にﾌﾞﾛｯｸ")
#define STRING_OBJDATA_BB_03 TEXT("地面と天井にﾌﾞﾛｯｸ")
#define STRING_OBJDATA_BB_04 TEXT("地面と天井(3)にﾌﾞﾛｯｸ")
#define STRING_OBJDATA_BB_05 TEXT("地面と天井(4)にﾌﾞﾛｯｸ")
#define STRING_OBJDATA_BB_06 TEXT("地面と天井(8)にﾌﾞﾛｯｸ")
#define STRING_OBJDATA_BB_07 TEXT("地面(4)と天井にﾌﾞﾛｯｸ")
#define STRING_OBJDATA_BB_08 TEXT("地面(4)と天井(3)にﾌﾞﾛｯｸ")
#define STRING_OBJDATA_BB_09 TEXT("地面(4)と天井(4)にﾌﾞﾛｯｸ")
#define STRING_OBJDATA_BB_10 TEXT("地面(5)と天井にﾌﾞﾛｯｸ")
#define STRING_OBJDATA_BB_11 TEXT("天井にﾌﾞﾛｯｸ")
#define STRING_OBJDATA_BB_12 TEXT("地面(5)と天井(4)にﾌﾞﾛｯｸ")
#define STRING_OBJDATA_BB_13 TEXT("地面(8)と天井にﾌﾞﾛｯｸ")
#define STRING_OBJDATA_BB_14 TEXT("地面と天井とその間(5)にﾌﾞﾛｯｸ")
#define STRING_OBJDATA_BB_15 TEXT("地面と天井とその間(4)にﾌﾞﾛｯｸ")
#define STRING_OBJDATA_BB_16 TEXT("すべてﾌﾞﾛｯｸ")

#define STRING_OBJDATA_T_01 TEXT("無し")
#define STRING_OBJDATA_T_02 TEXT("400")
#define STRING_OBJDATA_T_03 TEXT("300")
#define STRING_OBJDATA_T_04 TEXT("200")

#define STRING_OBJDATA_P_01 TEXT("高さ-1、横位置1.5")
#define STRING_OBJDATA_P_02 TEXT("ｴﾘｱの始まり：×。他ﾙｰﾑからの移動：高さ-1、横位置1.5")
#define STRING_OBJDATA_P_03 TEXT("高さ10、横位置1.5")
#define STRING_OBJDATA_P_04 TEXT("高さ4 、横位置1.5")
//#define STRING_OBJDATA_P_05 TEXT("高さ-1、横位置1.5"0
//#define STRING_OBJDATA_P_06 TEXT("高さ-1、横位置1.5")
#define STRING_OBJDATA_P_07 TEXT("高さ10、横位置1.5(自動歩行)")
//#define STRING_OBJDATA_P_08 TEXT("高さ10、横位置1.5(自動歩行)")

#define STRING_OBJDATA_BC_01 TEXT("青空")
#define STRING_OBJDATA_BC_02 TEXT("海")
#define STRING_OBJDATA_BC_03 TEXT("城壁")
#define STRING_OBJDATA_BC_04 TEXT("高さ11の川")
#define STRING_OBJDATA_BC_05 TEXT("夜")
#define STRING_OBJDATA_BC_06 TEXT("緑色の背景色(土管や山などを白に変更)")
#define STRING_OBJDATA_BC_07 TEXT("青い背景色を黒に、緑色の背景色を白に変更")
#define STRING_OBJDATA_BC_08 TEXT("青い背景色を黒に、緑色の背景色を白に、茶色を白に変更")

#define STRING_OBJDATA_MT_01 TEXT("緑色のｱｽﾚﾁｯｸ面")
#define STRING_OBJDATA_MT_02 TEXT("橙色のｱｽﾚﾁｯｸ面")
#define STRING_OBJDATA_MT_03 TEXT("大砲面")
#define STRING_OBJDATA_MT_04 TEXT("雲面")

#define STRING_OBJDATA_V_01 TEXT("無し")
#define STRING_OBJDATA_V_02 TEXT("空")
#define STRING_OBJDATA_V_03 TEXT("山")
#define STRING_OBJDATA_V_04 TEXT("柵のある庭")

#define STRING_OBJDATA_BADGUYS_01 TEXT("青いﾉｺﾉｺ")
#define STRING_OBJDATA_BADGUYS_02 TEXT("赤いﾉｺﾉｺ")
#define STRING_OBJDATA_BADGUYS_03 TEXT("ﾒｯﾄ")
#define STRING_OBJDATA_BADGUYS_04 TEXT("赤いﾉｺﾉｺ(往復)")
#define STRING_OBJDATA_BADGUYS_05 TEXT("青いﾉｺﾉｺ(停止)")
#define STRING_OBJDATA_BADGUYS_06 TEXT("ﾊﾝﾏｰﾌﾞﾛｽ")
#define STRING_OBJDATA_BADGUYS_07 TEXT("ｸﾘﾎﾞｰ")
#define STRING_OBJDATA_BADGUYS_08 TEXT("ｹﾞｯｿｰ")
#define STRING_OBJDATA_BADGUYS_09 TEXT("ｷﾗｰ")
#define STRING_OBJDATA_BADGUYS_10 TEXT("青いﾊﾟﾀﾊﾟﾀ(停止)")
#define STRING_OBJDATA_BADGUYS_11 TEXT("青いﾌﾟｸﾌﾟｸ(直進)")
#define STRING_OBJDATA_BADGUYS_12 TEXT("赤いﾌﾟｸﾌﾟｸ(直進)")
#define STRING_OBJDATA_BADGUYS_13 TEXT("ﾊﾞﾌﾞﾙ")
#define STRING_OBJDATA_BADGUYS_14 TEXT("ﾊﾟｯｸﾝﾌﾗﾜｰ")
#define STRING_OBJDATA_BADGUYS_15 TEXT("青いﾊﾟﾀﾊﾟﾀ(跳ねる)")
#define STRING_OBJDATA_BADGUYS_16 TEXT("赤いﾊﾟﾀﾊﾟﾀ(上下)")
#define STRING_OBJDATA_BADGUYS_17 TEXT("青いﾊﾟﾀﾊﾟﾀ(左右)")
#define STRING_OBJDATA_BADGUYS_18 TEXT("ｼﾞｭｹﾞﾑ")
#define STRING_OBJDATA_BADGUYS_19 TEXT("ﾄｹﾞｿﾞｰ(停止)")
#define STRING_OBJDATA_BADGUYS_20 TEXT("*ｶﾗｽみたいな赤いﾉｺﾉｺ")
#define STRING_OBJDATA_BADGUYS_21 TEXT("赤いﾌﾟｸﾌﾟｸ(空飛、連続)")
#define STRING_OBJDATA_BADGUYS_22 TEXT("ｸｯﾊﾟの炎")
#define STRING_OBJDATA_BADGUYS_23 TEXT("*暴走")
#define STRING_OBJDATA_BADGUYS_24 TEXT("ｷﾗｰ(ﾌﾟｸﾌﾟｸ)連続")
#define STRING_OBJDATA_BADGUYS_25 TEXT("*無し")
//#define STRING_OBJDATA_BADGUYS_26 TEXT("*無し")
//#define STRING_OBJDATA_BADGUYS_27 TEXT("*無し")
#define STRING_OBJDATA_BADGUYS_28 TEXT("ﾌｧｲｱｰﾊﾞｰ(右回転)")
#define STRING_OBJDATA_BADGUYS_29 TEXT("ﾌｧｲｱｰﾊﾞｰ(右高速回転)")
#define STRING_OBJDATA_BADGUYS_30 TEXT("ﾌｧｲｱｰﾊﾞｰ(左回転)")
#define STRING_OBJDATA_BADGUYS_31 TEXT("ﾌｧｲｱｰﾊﾞｰ(左高速回転)")
#define STRING_OBJDATA_BADGUYS_32 TEXT("ﾛﾝｸﾞﾌｧｲｱｰﾊﾞｰ（右回転)")
#define STRING_OBJDATA_BADGUYS_33 TEXT("ﾌｧｲｱｰﾊﾞｰ")
//#define STRING_OBJDATA_BADGUYS_34 TEXT("ﾌｧｲｱｰﾊﾞｰ")
//#define STRING_OBJDATA_BADGUYS_35 TEXT("ﾌｧｲｱｰﾊﾞｰ")
//#define STRING_OBJDATA_BADGUYS_36 TEXT("*無し")
#define STRING_OBJDATA_BADGUYS_37 TEXT("ﾘﾌﾄ(天秤)")
#define STRING_OBJDATA_BADGUYS_38 TEXT("ﾘﾌﾄ(上下)")
#define STRING_OBJDATA_BADGUYS_39 TEXT("ﾘﾌﾄ(上昇)")
#define STRING_OBJDATA_BADGUYS_40 TEXT("ﾘﾌﾄ(下降)")
#define STRING_OBJDATA_BADGUYS_41 TEXT("ﾘﾌﾄ(左右)")
#define STRING_OBJDATA_BADGUYS_42 TEXT("ﾘﾌﾄ(落下)")
#define STRING_OBJDATA_BADGUYS_43 TEXT("ﾘﾌﾄ(前進)")
#define STRING_OBJDATA_BADGUYS_44 TEXT("小さいﾘﾌﾄ(上昇)")
#define STRING_OBJDATA_BADGUYS_45 TEXT("小さいﾘﾌﾄ(下降)")
#define STRING_OBJDATA_BADGUYS_46 TEXT("ｸｯﾊﾟ")
#define STRING_OBJDATA_BADGUYS_47 TEXT("*生きているｷﾉｺ")
#define STRING_OBJDATA_BADGUYS_48 TEXT("*ｷﾉｺの出る音だけ")
//#define STRING_OBJDATA_BADGUYS_49 TEXT("*無し")
//#define STRING_OBJDATA_BADGUYS_50 TEXT("*無し")
#define STRING_OBJDATA_BADGUYS_51 TEXT("にせｼﾞｬﾝﾌﾟ台")
//#define STRING_OBJDATA_BADGUYS_52 TEXT("*無し")
#define STRING_OBJDATA_BADGUYS_53 TEXT("ﾜｰﾌﾟｿﾞｰﾝ")
#define STRING_OBJDATA_BADGUYS_54 TEXT("ｷﾉﾋﾟｵ(ﾋﾟｰﾁ姫)")
//#define STRING_OBJDATA_BADGUYS_55 TEXT("*暴走")
#define STRING_OBJDATA_BADGUYS_56 TEXT("2体のｸﾘﾎﾞｰ(縦位置10)")
#define STRING_OBJDATA_BADGUYS_57 TEXT("3体のｸﾘﾎﾞｰ(縦位置10)")
#define STRING_OBJDATA_BADGUYS_58 TEXT("2体のｸﾘﾎﾞｰ(縦位置6)")
#define STRING_OBJDATA_BADGUYS_59 TEXT("3体のｸﾘﾎﾞｰ(縦位置6)")
#define STRING_OBJDATA_BADGUYS_60 TEXT("2体の青いﾉｺﾉｺ(縦位置10)")
#define STRING_OBJDATA_BADGUYS_61 TEXT("3体の青いﾉｺﾉｺ(縦位置10)")
#define STRING_OBJDATA_BADGUYS_62 TEXT("2体の青いﾉｺﾉｺ(縦位置6)")
#define STRING_OBJDATA_BADGUYS_63 TEXT("3体の青いﾉｺﾉｺ(縦位置6)")
//#define STRING_OBJDATA_BADGUYS_64 TEXT("*無し")

// delreg.exe
#define STRING_DELREG_TITLE    TEXT("SMB Utility ﾚｼﾞｽﾄﾘの削除")
#define STRING_DELREG_CONFIRM  TEXT("SMB Utilityで使用したﾚｼﾞｽﾄﾘのｷｰを削除しますか？")
#define STRING_DELREG_COMPLETE TEXT("SMB Utilityで使用したﾚｼﾞｽﾄﾘのｷｰを削除しました。")
#define STRING_DELREG_ERROR_01 TEXT("SMB Utilityのﾚｼﾞｽﾄﾘのｷｰは、存在しません。")

#endif
